# https://medium.com/swlh/setting-up-github-actions-for-go-project-ea84f4ed3a40
name: Development CI/CD
on: 
  push: 
    branches: 
    — main 
  pull_request: 
    branches: 
    — main 

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Hello_World
        run: |
          echo 'hello world'

      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ‘1.18.0’

      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      - name: Run build
        run: make build

      - name: Run vet & lint
        run: |
          go vet .
          golint .

      - name: Run test
        run: |
          make test